/**
 * PipelinePressureService
 *
 * Prevents companies, deals, and relationships from going stale.
 * Computes pressure levels, scans for stalled entities, and creates
 * follow-up tasks automatically.
 *
 * Thresholds are sourced from CadenceThresholds — do not add magic numbers here.
 * TimingEngine handles SLA state calculations for individual entities.
 */

import { RELATIONSHIP_THRESHOLDS, DEAL_STAGE_THRESHOLDS } from './CadenceThresholds.js';
import { calcDealVelocityState, calcDealHeat }            from './TimingEngine.js';

// Derive cooling/stalled day thresholds from relationship profile "default"
const _COOLING_HOURS = RELATIONSHIP_THRESHOLDS.silence_hours.default;          // 336h = 14d
const _STALLED_HOURS = _COOLING_HOURS * RELATIONSHIP_THRESHOLDS.stalled_multiplier; // 840h = 35d

const COOLING_DAYS = Math.round(_COOLING_HOURS / 24);  // 14
const STALLED_DAYS = Math.round(_STALLED_HOURS / 24);  // 35

// ─── Pressure computation ─────────────────────────────────────────────────────

export function computePressureLevel(daysSince) {
  if (daysSince >= STALLED_DAYS)  return 'stalled';
  if (daysSince >= COOLING_DAYS)  return 'cooling';
  return 'active';
}

export function daysSinceDate(isoDate) {
  if (!isoDate) return 999;
  const ms = Date.now() - new Date(isoDate).getTime();
  return Math.max(0, Math.floor(ms / 86400000));
}

// ─── Scan store for stalled entities ─────────────────────────────────────────

export function scanForStalledEntities(store) {
  const companies = store.companies || [];
  const deals     = store.deals     || [];
  const contacts  = store.contacts  || [];

  const stalledCompanies = companies.filter((c) => {
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    return days >= STALLED_DAYS;
  });

  const stalledDeals = deals.filter((d) => {
    if (d.stage === 'closed' || d.stage === 'lost') return false;
    // Use TimingEngine for deal velocity where possible
    const velocityResult = calcDealVelocityState(d);
    return velocityResult.velocity_state === 'slow' || velocityResult.velocity_state === 'critical';
  });

  const stalledContacts = contacts.filter((c) => {
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    return days >= STALLED_DAYS;
  });

  const coolingRelationships = contacts.filter((c) => {
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    return days >= COOLING_DAYS && days < STALLED_DAYS;
  });

  return { stalledCompanies, stalledDeals, stalledContacts, coolingRelationships };
}

// ─── Auto-create follow-up tasks ──────────────────────────────────────────────

export function createFollowUpTasks(stalledEntities, store, uid, nowIso) {
  const { stalledCompanies, stalledDeals, stalledContacts } = stalledEntities;
  const created = [];

  for (const company of stalledCompanies.slice(0, 5)) {
    const title = `Follow up with ${company.ownerName || company.name} owner`;
    const dupe  = (store.tasks || []).some(
      (t) => t.linkedEntityId === company.id && t.status !== 'done' && t.status !== 'archived' && t.title === title
    );
    if (dupe) continue;
    const task = {
      id:               uid(),
      title,
      description:      `${company.name} has had no interaction in ${STALLED_DAYS}+ days. Re-engage to maintain pipeline momentum.`,
      priority:         'high',
      status:           'todo',
      linkedEntityType: 'company',
      linkedEntityId:   company.id,
      dueDate:          new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      createdAt:        nowIso(),
      updatedAt:        nowIso(),
      autoGenerated:    true,
      source:           'pipeline_pressure',
    };
    store.tasks.push(task);
    created.push(task);
  }

  for (const deal of stalledDeals.slice(0, 5)) {
    const title = `Re-engage stalled deal: ${deal.companyName}`;
    const dupe  = (store.tasks || []).some(
      (t) => t.linkedEntityId === deal.id && t.status !== 'done' && t.status !== 'archived' && t.title === title
    );
    if (dupe) continue;
    const velocityResult = calcDealVelocityState(deal);
    const task = {
      id:               uid(),
      title,
      description:      `Deal "${deal.companyName}" in stage "${deal.stage}" has been slow/critical (${velocityResult.days_in_stage?.toFixed(0) ?? '?'} days). Review and advance.`,
      priority:         velocityResult.velocity_state === 'critical' ? 'critical' : 'high',
      status:           'todo',
      linkedEntityType: 'deal',
      linkedEntityId:   deal.id,
      dueDate:          new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      createdAt:        nowIso(),
      updatedAt:        nowIso(),
      autoGenerated:    true,
      source:           'pipeline_pressure',
    };
    store.tasks.push(task);
    created.push(task);
  }

  for (const contact of stalledContacts.slice(0, 5)) {
    const name  = [contact.firstName, contact.lastName].filter(Boolean).join(' ');
    const title = `Follow up with ${name}`;
    const dupe  = (store.tasks || []).some(
      (t) => t.linkedEntityId === contact.id && t.status !== 'done' && t.status !== 'archived' && t.title === title
    );
    if (dupe) continue;
    const task = {
      id:               uid(),
      title,
      description:      `Contact has had no interaction in ${STALLED_DAYS}+ days. Reconnect to maintain relationship strength.`,
      priority:         'medium',
      status:           'todo',
      linkedEntityType: 'contact',
      linkedEntityId:   contact.id,
      dueDate:          new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      createdAt:        nowIso(),
      updatedAt:        nowIso(),
      autoGenerated:    true,
      source:           'pipeline_pressure',
    };
    store.tasks.push(task);
    created.push(task);
  }

  return created;
}

// ─── Update pressure levels on all entities in-place ────────────────────────

export function updatePressureLevels(store) {
  for (let i = 0; i < (store.companies || []).length; i++) {
    const c    = store.companies[i];
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    store.companies[i] = { ...c, pipelinePressureLevel: computePressureLevel(days), daysSinceLastInteraction: days };
  }
  for (let i = 0; i < (store.contacts || []).length; i++) {
    const c    = store.contacts[i];
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    store.contacts[i] = { ...c, pipelinePressureLevel: computePressureLevel(days), daysSinceLastInteraction: days };
  }
  for (let i = 0; i < (store.deals || []).length; i++) {
    const d    = store.deals[i];
    const days = daysSinceDate(d.lastInteractionAt || d.updatedAt);
    const heat = calcDealHeat(d);
    store.deals[i] = {
      ...d,
      pipelinePressureLevel:  computePressureLevel(days),
      daysSinceLastInteraction: days,
      heat_state:             heat.heat_state,
    };
  }
}

// ─── Dashboard metrics ────────────────────────────────────────────────────────

export function getDashboardMetrics(store) {
  const { stalledCompanies, stalledDeals, stalledContacts, coolingRelationships } = scanForStalledEntities(store);
  return {
    stalledCompaniesCount:     stalledCompanies.length,
    stalledDealsCount:         stalledDeals.length,
    stalledContactsCount:      stalledContacts.length,
    coolingRelationshipsCount: coolingRelationships.length,
  };
}

// ─── Deal velocity (now delegates to TimingEngine) ────────────────────────────

export function checkDealVelocity(deals) {
  return (deals || [])
    .filter((d) => d.stage !== 'closed' && d.stage !== 'lost')
    .map((d) => {
      const result = calcDealVelocityState(d);
      return {
        dealId:           d.id,
        companyName:      d.companyName,
        stage:            d.stage,
        stageDurationDays: result.days_in_stage,
        velocity_state:   result.velocity_state,
        risk_level:       result.risk_level,
        // legacy field — true when not healthy
        slowMoving:       result.velocity_state !== 'healthy',
      };
    });
}

// ─── Acquisition scoreboard ───────────────────────────────────────────────────

export function computeScoreboard(store) {
  const companies   = store.companies   || [];
  const deals       = store.deals       || [];
  const meetings    = store.meetings    || [];
  const interactions = store.interactions || [];

  const CONTACTED_STATUSES = new Set(['contacted', 'conversation', 'interested', 'diligence', 'under_loi', 'under_contract', 'closed']);
  const CONV_STATUSES      = new Set(['conversation', 'interested', 'diligence', 'under_loi', 'under_contract', 'closed']);
  const LOI_STAGES         = new Set(['loi_discussion', 'loi_signed', 'due_diligence', 'financing', 'closing', 'closed']);

  return {
    targetsFound:        companies.length,
    ownersContacted:     companies.filter((c) => CONTACTED_STATUSES.has(c.status)).length,
    conversationsStarted:companies.filter((c) => CONV_STATUSES.has(c.status)).length,
    meetingsHeld:        meetings.length,
    dealsEvaluated:      deals.length,
    LOIsSubmitted:       deals.filter((d) => LOI_STAGES.has(d.stage)).length,
    dealsClosed:         deals.filter((d) => d.stage === 'closed').length,
    emailsSentThisWeek:  interactions.filter((i) => {
      const age = daysSinceDate(i.createdAt);
      return age < 7 && i.direction === 'outbound' && (i.type === 'email' || i.interactionType === 'email');
    }).length,
    repliesThisWeek: interactions.filter((i) => {
      const age = daysSinceDate(i.createdAt);
      return age < 7 && i.direction === 'inbound';
    }).length,
    updatedAt: new Date().toISOString(),
  };
}

// ─── Conversation funnel ──────────────────────────────────────────────────────

export function computeConversationFunnel(store) {
  const companies    = store.companies    || [];
  const meetings     = store.meetings     || [];
  const deals        = store.deals        || [];
  const interactions = store.interactions || [];

  const emailsSent   = interactions.filter((i) => i.direction === 'outbound' && (i.type === 'email' || i.interactionType === 'email')).length;
  const repliesRecv  = interactions.filter((i) => i.direction === 'inbound').length;
  const mtgsScheduled = meetings.length;
  const dealsProgressing = deals.filter((d) => !['identified', 'lost'].includes(d.stage)).length;

  const ownersContacted = companies.filter((c) => {
    const s = c.sellerConversationStatus;
    return s && s !== 'not_contacted';
  }).length;

  const replyRate   = emailsSent   > 0 ? parseFloat((repliesRecv / emailsSent * 100).toFixed(1))  : 0;
  const meetingRate = repliesRecv  > 0 ? parseFloat((mtgsScheduled / repliesRecv * 100).toFixed(1)) : 0;

  return {
    companiesIdentified: companies.length,
    ownersContacted,
    repliesReceived:     repliesRecv,
    meetingsScheduled:   mtgsScheduled,
    dealsProgressing,
    emailsSent,
    replyRate,
    meetingRate,
  };
}

// ─── Contact frequency progress ───────────────────────────────────────────────

export function computeFrequencyProgress(store) {
  const interactions = store.interactions || [];
  const tasks        = store.tasks        || [];
  const contacts     = store.contacts     || [];
  const settings     = store.settings     || {};

  const ownersTarget    = settings.ownersContactedPerWeek ?? 25;
  const followUpsTarget = settings.followUpsPerDay        ?? 5;
  const boardTarget     = settings.boardOutreachPerWeek   ?? 3;

  const thisWeekStart = Date.now() - 7 * 86400000;
  const todayStart    = new Date(); todayStart.setHours(0, 0, 0, 0);

  const ownersThisWeek = interactions.filter((i) => {
    return i.direction === 'outbound' && new Date(i.createdAt).getTime() > thisWeekStart;
  }).length;

  const followUpsToday = tasks.filter((t) => {
    if (t.status !== 'done') return false;
    if (!t.completedAt) return false;
    return new Date(t.completedAt) >= todayStart;
  }).length;

  const boardOutreachThisWeek = interactions.filter((i) => {
    const contact = contacts.find((c) => c.id === i.contactId);
    return contact?.contactType === 'board_candidate' && new Date(i.createdAt).getTime() > thisWeekStart;
  }).length;

  return {
    ownersContactedPerWeek: { current: ownersThisWeek,       target: ownersTarget,    label: `Owners contacted this week: ${ownersThisWeek} / ${ownersTarget}` },
    followUpsPerDay:        { current: followUpsToday,        target: followUpsTarget, label: `Follow-ups today: ${followUpsToday} / ${followUpsTarget}` },
    boardOutreachPerWeek:   { current: boardOutreachThisWeek, target: boardTarget,     label: `Board outreach this week: ${boardOutreachThisWeek} / ${boardTarget}` },
  };
}

const PipelinePressureService = {
  computePressureLevel,
  daysSinceDate,
  scanForStalledEntities,
  createFollowUpTasks,
  updatePressureLevels,
  getDashboardMetrics,
  checkDealVelocity,
  computeScoreboard,
  computeConversationFunnel,
  computeFrequencyProgress,
};

export default PipelinePressureService;

export function daysSinceDate(isoDate) {
  if (!isoDate) return 999;
  const ms = Date.now() - new Date(isoDate).getTime();
  return Math.max(0, Math.floor(ms / 86400000));
}

// ─── Scan store for stalled entities ─────────────────────────────────────────

export function scanForStalledEntities(store) {
  const companies = store.companies || [];
  const deals     = store.deals     || [];
  const contacts  = store.contacts  || [];

  const stalledCompanies = companies.filter((c) => {
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    return days >= 21;
  });

  const stalledDeals = deals.filter((d) => {
    if (d.stage === 'closed' || d.stage === 'lost') return false;
    const days = daysSinceDate(d.lastInteractionAt || d.updatedAt);
    return days >= 21;
  });

  const stalledContacts = contacts.filter((c) => {
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    return days >= 21;
  });

  const coolingRelationships = contacts.filter((c) => {
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    return days >= 7 && days < 21;
  });

  return { stalledCompanies, stalledDeals, stalledContacts, coolingRelationships };
}

// ─── Auto-create follow-up tasks ──────────────────────────────────────────────

export function createFollowUpTasks(stalledEntities, store, uid, nowIso) {
  const { stalledCompanies, stalledDeals, stalledContacts } = stalledEntities;
  const created = [];

  for (const company of stalledCompanies.slice(0, 5)) {
    const title = `Follow up with ${company.ownerName || company.name} owner`;
    const dupe  = (store.tasks || []).some(
      (t) => t.linkedEntityId === company.id && t.status !== 'done' && t.status !== 'archived' && t.title === title
    );
    if (dupe) continue;
    const task = {
      id:               uid(),
      title,
      description:      `${company.name} has had no interaction in 21+ days. Re-engage to maintain pipeline momentum.`,
      priority:         'high',
      status:           'todo',
      linkedEntityType: 'company',
      linkedEntityId:   company.id,
      dueDate:          new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      createdAt:        nowIso(),
      updatedAt:        nowIso(),
      autoGenerated:    true,
    };
    store.tasks.push(task);
    created.push(task);
  }

  for (const deal of stalledDeals.slice(0, 5)) {
    const title = `Re-engage stalled deal: ${deal.companyName}`;
    const dupe  = (store.tasks || []).some(
      (t) => t.linkedEntityId === deal.id && t.status !== 'done' && t.status !== 'archived' && t.title === title
    );
    if (dupe) continue;
    const task = {
      id:               uid(),
      title,
      description:      `Deal "${deal.companyName}" has stalled for 21+ days. Review status and advance to next stage.`,
      priority:         'high',
      status:           'todo',
      linkedEntityType: 'deal',
      linkedEntityId:   deal.id,
      dueDate:          new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      createdAt:        nowIso(),
      updatedAt:        nowIso(),
      autoGenerated:    true,
    };
    store.tasks.push(task);
    created.push(task);
  }

  for (const contact of stalledContacts.slice(0, 5)) {
    const name  = [contact.firstName, contact.lastName].filter(Boolean).join(' ');
    const title = `Follow up with ${name}`;
    const dupe  = (store.tasks || []).some(
      (t) => t.linkedEntityId === contact.id && t.status !== 'done' && t.status !== 'archived' && t.title === title
    );
    if (dupe) continue;
    const task = {
      id:               uid(),
      title,
      description:      `Contact has had no interaction in 21+ days. Reconnect to maintain relationship strength.`,
      priority:         'medium',
      status:           'todo',
      linkedEntityType: 'contact',
      linkedEntityId:   contact.id,
      dueDate:          new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      createdAt:        nowIso(),
      updatedAt:        nowIso(),
      autoGenerated:    true,
    };
    store.tasks.push(task);
    created.push(task);
  }

  return created;
}

// ─── Update pressure levels on all entities in-place ────────────────────────

export function updatePressureLevels(store) {
  for (let i = 0; i < (store.companies || []).length; i++) {
    const c    = store.companies[i];
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    store.companies[i] = { ...c, pipelinePressureLevel: computePressureLevel(days), daysSinceLastInteraction: days };
  }
  for (let i = 0; i < (store.contacts || []).length; i++) {
    const c    = store.contacts[i];
    const days = daysSinceDate(c.lastInteractionAt || c.updatedAt);
    store.contacts[i] = { ...c, pipelinePressureLevel: computePressureLevel(days), daysSinceLastInteraction: days };
  }
  for (let i = 0; i < (store.deals || []).length; i++) {
    const d    = store.deals[i];
    const days = daysSinceDate(d.lastInteractionAt || d.updatedAt);
    store.deals[i] = { ...d, pipelinePressureLevel: computePressureLevel(days), daysSinceLastInteraction: days };
  }
}

// ─── Dashboard metrics ────────────────────────────────────────────────────────

export function getDashboardMetrics(store) {
  const { stalledCompanies, stalledDeals, stalledContacts, coolingRelationships } = scanForStalledEntities(store);
  return {
    stalledCompaniesCount:     stalledCompanies.length,
    stalledDealsCount:         stalledDeals.length,
    stalledContactsCount:      stalledContacts.length,
    coolingRelationshipsCount: coolingRelationships.length,
  };
}

// ─── Deal velocity ────────────────────────────────────────────────────────────

const VELOCITY_THRESHOLDS = {
  discovery:      14,
  due_diligence:  30,
  financing:      30,
};

export function checkDealVelocity(deals) {
  return (deals || [])
    .filter((d) => d.stage !== 'closed' && d.stage !== 'lost')
    .map((d) => {
      const days      = d.stageEnteredAt ? daysSinceDate(d.stageEnteredAt) : daysSinceDate(d.updatedAt);
      const threshold = VELOCITY_THRESHOLDS[d.stage] ?? null;
      return {
        dealId:          d.id,
        companyName:     d.companyName,
        stage:           d.stage,
        stageDurationDays: days,
        threshold,
        slowMoving:      threshold !== null && days > threshold,
      };
    });
}

// ─── Acquisition scoreboard ───────────────────────────────────────────────────

export function computeScoreboard(store) {
  const companies   = store.companies   || [];
  const deals       = store.deals       || [];
  const meetings    = store.meetings    || [];
  const interactions = store.interactions || [];

  const CONTACTED_STATUSES = new Set(['contacted', 'conversation', 'interested', 'diligence', 'under_loi', 'under_contract', 'closed']);
  const CONV_STATUSES      = new Set(['conversation', 'interested', 'diligence', 'under_loi', 'under_contract', 'closed']);
  const LOI_STAGES         = new Set(['loi_discussion', 'loi_signed', 'due_diligence', 'financing', 'closing', 'closed']);

  return {
    targetsFound:        companies.length,
    ownersContacted:     companies.filter((c) => CONTACTED_STATUSES.has(c.status)).length,
    conversationsStarted:companies.filter((c) => CONV_STATUSES.has(c.status)).length,
    meetingsHeld:        meetings.length,
    dealsEvaluated:      deals.length,
    LOIsSubmitted:       deals.filter((d) => LOI_STAGES.has(d.stage)).length,
    dealsClosed:         deals.filter((d) => d.stage === 'closed').length,
    // weekly window metrics
    emailsSentThisWeek:  interactions.filter((i) => {
      const age = daysSinceDate(i.createdAt);
      return age < 7 && i.direction === 'outbound' && (i.type === 'email' || i.interactionType === 'email');
    }).length,
    repliesThisWeek: interactions.filter((i) => {
      const age = daysSinceDate(i.createdAt);
      return age < 7 && i.direction === 'inbound';
    }).length,
    updatedAt: new Date().toISOString(),
  };
}

// ─── Conversation funnel ──────────────────────────────────────────────────────

export function computeConversationFunnel(store) {
  const companies    = store.companies    || [];
  const meetings     = store.meetings     || [];
  const deals        = store.deals        || [];
  const interactions = store.interactions || [];

  const emailsSent   = interactions.filter((i) => i.direction === 'outbound' && (i.type === 'email' || i.interactionType === 'email')).length;
  const repliesRecv  = interactions.filter((i) => i.direction === 'inbound').length;
  const mtgsScheduled = meetings.length;
  const dealsProgressing = deals.filter((d) => !['identified', 'lost'].includes(d.stage)).length;

  const ownersContacted = companies.filter((c) => {
    const s = c.sellerConversationStatus;
    return s && s !== 'not_contacted';
  }).length;

  const replyRate   = emailsSent   > 0 ? parseFloat((repliesRecv / emailsSent * 100).toFixed(1))  : 0;
  const meetingRate = repliesRecv  > 0 ? parseFloat((mtgsScheduled / repliesRecv * 100).toFixed(1)) : 0;

  return {
    companiesIdentified: companies.length,
    ownersContacted,
    repliesReceived:     repliesRecv,
    meetingsScheduled:   mtgsScheduled,
    dealsProgressing,
    emailsSent,
    replyRate,
    meetingRate,
  };
}

// ─── Contact frequency progress ───────────────────────────────────────────────

export function computeFrequencyProgress(store) {
  const interactions = store.interactions || [];
  const tasks        = store.tasks        || [];
  const contacts     = store.contacts     || [];
  const settings     = store.settings     || {};

  const ownersTarget   = settings.ownersContactedPerWeek ?? 25;
  const followUpsTarget = settings.followUpsPerDay        ?? 5;
  const boardTarget    = settings.boardOutreachPerWeek    ?? 3;

  const thisWeekStart = Date.now() - 7 * 86400000;
  const todayStart    = new Date(); todayStart.setHours(0, 0, 0, 0);

  const ownersThisWeek = interactions.filter((i) => {
    return i.direction === 'outbound' && new Date(i.createdAt).getTime() > thisWeekStart;
  }).length;

  const followUpsToday = tasks.filter((t) => {
    if (t.status !== 'done') return false;
    if (!t.completedAt) return false;
    return new Date(t.completedAt) >= todayStart;
  }).length;

  const boardContacts = contacts.filter((c) => c.contactType === 'board_candidate').length;
  const boardOutreachThisWeek = interactions.filter((i) => {
    const contact = contacts.find((c) => c.id === i.contactId);
    return contact?.contactType === 'board_candidate' && new Date(i.createdAt).getTime() > thisWeekStart;
  }).length;

  return {
    ownersContactedPerWeek:  { current: ownersThisWeek,        target: ownersTarget,    label: `Owners contacted this week: ${ownersThisWeek} / ${ownersTarget}` },
    followUpsPerDay:         { current: followUpsToday,         target: followUpsTarget, label: `Follow-ups today: ${followUpsToday} / ${followUpsTarget}` },
    boardOutreachPerWeek:    { current: boardOutreachThisWeek,  target: boardTarget,     label: `Board outreach this week: ${boardOutreachThisWeek} / ${boardTarget}` },
  };
}

const PipelinePressureService = {
  computePressureLevel,
  daysSinceDate,
  scanForStalledEntities,
  createFollowUpTasks,
  updatePressureLevels,
  getDashboardMetrics,
  checkDealVelocity,
  computeScoreboard,
  computeConversationFunnel,
  computeFrequencyProgress,
};

export default PipelinePressureService;
